### ISSUE TITLE
code releasing

### ISSUE THREAD

**Issue by pokameng** [KU-CVLAB/DiffMatch#2]
@gseonglee 
hello, bro!
Thanks for your great work! By the way, when will the code be released?

**Comment by nam-jisu** [comment]
Thanks so much for taking an interest in our work! We're right in the middle of refining the code and running additional experiments for public release in the next 1 to 2 months.

**Comment by VLadImirluren** [comment]
> Thanks so much for taking an interest in our work! We're right in the middle of refining the code and running additional experiments for public release in the next 1 to 2 months.

hey! Nice work~ I think the code release time is coming! yeah?
I am so excited. Looking for your code~
Best wishes~

**Comment by dadwadw233** [comment]
Is there any news about the code？🤕 
Can't wait to try it.

**Comment by nam-jisu** [comment]
Thank you for your interest in our paper. We have released the code and pre-trained model weights. We hope you find our code useful. Please feel free to reach out if you have any questions.
